### ISSUE TITLE
"Shutter as default" old layout

### ISSUE THREAD

**Issue by ultrazebra** [Photon89/shutter-jekyll-site#71] opened 2023-09-25 18:20 UTC
https://shutter-project.org/faq-help/set-shutter-as-the-default-screenshot-tool redirects to old layout

**Comment by DarthGandalf** [comment] 2023-09-25 21:38
Dupe of #32 

Would you like to implement that content on jekyll (the new layout)?

**Closed as completed by DarthGandalf** 2023-09-25 21:38 UTC
